### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by peterphji** [bhattsameer/Bombers#100]

**Comment by Cottonwoodhill** [comment]
Hi, there is defibitely no support here.... sad!

**Comment by Aky754** [comment]
Brother. ...commands to batao kayse turmux me use kiyaa .. jaai.. yaha koi comands hai bataooo

**Comment by Cottonwoodhill** [comment]
do you speak english?

**Comment by Cottonwoodhill** [comment]
Hi,
Thank you for your reply.
Well I am using the scrypts on a Debain machine.

**Comment by Cottonwoodhill** [comment]
here a re the command lines : 
![1](https://user-images.githubusercontent.com/37047745/160094176-689da66c-0f64-41a8-9ea4-9ed5d80a0c2e.JPG)

**Comment by Cottonwoodhill** [comment]
For Email Bomber : 

![3](https://user-images.githubusercontent.com/37047745/160095318-2397fad8-3ab2-4931-9a42-fb9704245524.JPG)
![4](https://user-images.githubusercontent.com/37047745/160095324-297089b5-442f-4b91-82fc-88cb85ee9ec7.JPG)

**Comment by Cottonwoodhill** [comment]
sow hat? Can you help me?
thanks

**Comment by Cottonwoodhill** [comment]
![1](https://user-images.githubusercontent.com/37047745/160233351-46b59d38-a128-4f0a-8ad1-fc4fbd28fe66.JPG)
Thy script doesn't start.

**Comment by Cottonwoodhill** [comment]
@peterphji

**Comment by Cottonwoodhill** [comment]
these scripts are a joke.

**Comment by bhattsameer** [comment]
hello @Cottonwoodhill, Thanks for your feedback, My apologies in delay in I was response away from github. I agree those initial scripts are not working it requires continues update, That is the main reason I have changed the goal of this repo to collection of such bomber scripts rather than keep updating them the initial one I created. Moreover, Pull requests are always appreciate in a support of this. Thanks in advance for your support and really appreciate your feedback.
